export type Album = {
  id: string;
  name: string;
  artist_name: string;
  release_date: string;
  url: string;
  track_count: number;
  genre_names: string[];
  copyright: string;
  record_label: string;
  artwork_url: string;
  artwork_width: number;
  artwork_height: number;
  artwork_bg_color: string;
  artwork_text_color1: string;
  artwork_text_color2: string;
  artwork_text_color3: string;
  artwork_text_color4: string;
  content_rating: string;
  editorial_notes_standard: string | null;
  editorial_notes_short: string | null;
  is_single: boolean;
  is_compilation: boolean;
  is_complete: boolean;
};
